version: 1
formatters:
  simple:
    class: logging.Formatter
    format: '%(name)s@%(funcName)s %(asctime)s %(levelname)s %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simple

  file:
    class: logging.FileHandler
    filename: ml_titanic.log
    formatter: simple

root:
  level: INFO
  handlers: [console, file]