tasks:
  - source: tasks.get
    product: output/get.parquet

  - source: tasks.features
    product: output/features.parquet

  - source: tasks.join
    product: output/join.parquet

  - source: fit.py
    name: fit
    product:
        nb: output/nb.html
        model: output/model.pickle
