meta:
  source_loader:
    module: ml_online

  import_tasks_from: pipeline-features.yaml


serializer: ml_online.io.serialize
unserializer: ml_online.io.unserialize

# clients:
#   File: ml_online.clients.get_s3

tasks:
  - source: ml_online.tasks.raw.get
    product: "{{product_root}}/products/raw/get.parquet"
    params:
      sample: '{{sample}}'
  
  - source: notebooks/fit.py
    product:
      nb: "{{product_root}}/products/report.html"
      model: "{{product_root}}/products/model.pickle"
