tasks:
  - source: raw.R
    product:
      nb: output/raw.ipynb
      data: output/raw.csv

  - source: clean.R
    product:
      nb: output/clean.ipynb
      data: output/clean.csv

  - source: plot.R
    product: output/plot.ipynb