tasks:
  # use plain R scripts
  - source: raw.R
    product:
      # this is the executed version of your script
      # you can review tables and charts here
      nb: output/raw.html
      data: output/raw.csv

  - source: clean.R
    product:
      nb: output/clean.html
      data: output/clean.csv

  # R markdown files also supported
  - source: plot.Rmd
    product: output/plot.html