tasks:
  - source: script.py
    product: output/nb-log.html
    papermill_params:
      log_output: True
    params:
      logging_level: '{{logging_level}}'

  - source: tasks.function
    product: output/fn-log.txt
    params:
      logging_level: '{{logging_level}}'
