name: mlflow

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pygraphviz

  - pip:
    - ploomber
    - pandas
    - scikit-learn
    - sklearn-evaluation
    - jupyter
    - mlflow
    # mlflow incompatibility: https://github.com/mlflow/mlflow/issues/9331
    - pydantic<2