executor: parallel

tasks:
  - source: tasks/load.py
    product:
      nb: products/load.html
      data: products/data.csv

  - source: tasks/fit.py
    name: fit-[[model]]
    product:
      nb: products/fit-[[model]].html
      model: products/model-[[model]].pkl
    grid:
      - model: [sklearn.ensemble.RandomForestClassifier]
        model_params:
          # optimize over these parameters
          - n_estimators: [2, 5]
            criterion: [gini, entropy]
    
      - model: [sklearn.svm.SVC]
        model_params:
          # optimize over these parameters
          - kernel: [linear, poly]
            C: [0.1, 1.0]
      
      
