tasks:
    # tasks.get, features and join are python functions
  - source: tasks.get
    product: output/get.parquet

  - source: tasks.features
    product: output/features.parquet

  - source: tasks.join
    product: output/join.parquet

    # fit.py is a script (that you can open as notebook in Jupyter)
  - source: fit.py
    name: fit-[[n_estimators]]
    product:
        # this output notebook is the model's evaluation report
        nb: output/nb-[[n_estimators]].html
        model: output/model-[[n_estimators]].pickle
    grid:
        n_estimators: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    # optional config to hide the code in the output/nb.html report
    nbconvert_export_kwargs:
      exclude_input: True